config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :fanclubs do
    resources :comments
    resources :fans
  end
  # resources :songs

  resources :bands do
    resources :comments
    resources :members
    resources :albums do
      resources :songs
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'bands#index'
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope { order(time: :asc) }

  has_many :comments, as: :commentable

  validates :name, presence: true, uniqueness: true
  validates_presence_of :time, :location
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :description, :location, :date, :time, :photo)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Event name' %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control', placeholder: 'Event location' %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.text_field :photo, class: 'form-control', placeholder: 'Event photo URL', value: 'https://static1.squarespace.com/static/52f3ba1fe4b0932b3f775421/t/530e5fa1e4b07a55c9b3d6ad/1393450915317/Beer+Die+Events.jpg?format=1500w' %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.datetime_select :time, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Event description' %>
  </div>

  <div class="actions" align="right">
    <%= f.submit 'Save', class: 'btn btn-primary btn-save' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">

  <%= link_to 'Back', event_path(@event), class: 'btn btn-outline-info btn-sm btn-back' %>

  <h1 class="form-header">Editing Event</h1>

  <%= render 'form', event: @event %>

</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-name" href="/bands">Fakezone</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link nav-normal" href="/bands">Bands <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link active nav-active" href="/events">Events</a>
        <a class="nav-item nav-link nav-normal" href="/fanclubs">Fanclubs</a>
      </div>
    </div>
  </nav>
</div>

<div class="container index">
  <%= link_to "Add Event", new_event_path, class: 'btn btn-outline-info' %>
  <br>
  <br>
  <div class="container">
    <div class="row">
      <div class="card-columns">
      <% @events.each do |event| %>

        <div class="card">
          <img class="card-img-top card-style" src=<%= event.photo %>>
          <div class="card-block card-div card-name">
              <h4 class="card-title"><%= link_to event.name, event %></h4>
              <p class="card-delete"><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %></p>
            <div class="clear: both;"></div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container" >

  <%= link_to 'Back', events_path, class: 'btn btn-outline-info btn-sm btn-back' %>

  <h1 class="form-header">Add Event</h1>

  <%= render 'form', event: @event %>
  
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-name" href="/bands">Fakezone</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link nav-normal" href="/bands">Bands <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link active nav-active" href="/events">Events</a>
        <a class="nav-item nav-link nav-normal" href="/fanclubs">Fanclubs</a>
      </div>
    </div>
  </nav>
</div>

<div class="container detail">
  <%= link_to 'Back', events_path, class: 'btn btn-outline-info btn-sm btn-back' %>
  <h2 class="detail-header"><%= @event.name %></h2>
  <br>
  <p class="event-info">
    <strong><%= @event.location %></strong>, <%= @event.time.strftime("%d.%m.%Y %H:%M") %>
  </p>
  <img class="detail-picture" src=<%= @event.photo %>>
  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>
  <p>
    <td><%= link_to "Edit Event", edit_event_path(@event), class: 'btn btn-primary' %></td>
  </p>
</div>

<div class="container comment">
  <h3>Comments</h3>

  <%= form_for [@event, Comment.new] do |f| %>
  <%= f.text_area :body, class: 'form-control', placeholder: "Add a comment" %><br/>
  <%= f.submit "Add Comment", class: 'btn btn-primary btn-save' %>
  <% end %>
  <ul>
    <%= render(partial: 'comments/comment', collection: @event.comments) %>
  </ul>
</div>