config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :fanclubs do
    resources :comments
    resources :fans
  end
  # resources :songs

  resources :bands do
    resources :comments
    resources :members
    resources :albums do
      resources :songs
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'bands#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band
  has_many :songs, dependent: :destroy
  default_scope { order(year: :desc) }

  validates_presence_of :band_id
  validates :name, presence: true, uniqueness: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @band = Band.find(params[:band_id])
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
    @band = Band.find(params[:band_id])
    @album = @band.albums.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @band = Band.find(params[:band_id])
    @album = @band.albums.new(album_params)

    if @album.save
      redirect_to band_path(@band)
    else
      render 'new'
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    @band = Band.find(params[:band_id])
    @album = @band.albums.find(params[:id])

    if @album.update(album_params)
      redirect_to band_path(@band)
    else
      render 'edit'
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @band = Band.find(params[:band_id])
    @album = @band.albums.find(params[:id]).destroy
    redirect_to band_path(@band)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @band = Band.find(params[:band_id])
    @album = @band.albums.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def album_params
    params.require(:album).permit(:name, :year, :photo, :description)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for [@band, album] do |f| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Album name' %>
  </div>

  <div class="form-group">
    <%= f.label :year %>
    <%= f.number_field :year, class: 'form-control', placeholder: 'Year album was published' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', placeholder: 'Album description' %>
  </div>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.text_field :photo, class: 'form-control', placeholder: 'Album photo URL', value: 'https://image.freepik.com/free-icon/music-album_318-43305.jpg' %>
  </div>

  <div class="actions" align="right">
    <%= f.submit 'Save', class: 'btn btn-primary btn-save' %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div class="container">

  <%= link_to 'Back', band_path(@band), class: 'btn btn-outline-info btn-sm btn-back' %>

  <h1 class="form-header">Editing Album</h1>

  <%= render 'form', album: @album %>

</div>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= album.year %></td>
        <td><%= album.photo %></td>
        <td><%= link_to 'Show', band_album(@album) %></td>
        <td><%= link_to 'Edit', edit_album_path(@album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<div class="container">

  <%= link_to 'Back', band_path(@band), class: 'btn btn-outline-info btn-sm btn-back' %>

  <h1 class="form-header">Add Album</h1>

  <%= render 'form', album: @album %>

</div>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-name" href="/bands">Fakezone</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active nav-active" href="/bands">Bands <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link nav-normal" href="/events">Events</a>
        <a class="nav-item nav-link nav-normal" href="/fanclubs">Fanclubs</a>
      </div>
    </div>
  </nav>
</div>

<div class="container detail">
  <%= link_to 'Back', band_path(@band), class: 'btn btn-outline-info btn-sm btn-back' %>
  <h2 class="detail-header"><%= @album.name %> (<%= @album.year %>)</h2>
  <img class="detail-picture" src=<%= @album.photo %>>
  <p><%= @album.description %></p>

  <br>
  <br>

  <%= link_to "Add Song", new_band_album_song_path(@band, @album, @song), class: 'btn btn-primary' %>
  <h3>Songs:</h3>
  <% if @album.songs.size > 0 %>
    <table class="table">
      <tr>
        <th>Number</th>
        <th>Name</th>
        <th>Duration</th>
        <th colspan="2"></th>
      </tr>
      <% @album.songs.each do |song| %>
      <tr>
        <td><%= song.number %></td>
        <td><%= song.name %></td>
        <td><%= song.duration %></td>
        <td><%= link_to "Edit Song", edit_band_album_song_path(@band, @album, song), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Remove Song', band_album_song_path(@band, @album, song), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %></td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>There are no songs yet.</p>
  <% end %>
</div>