config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :fanclubs do
    resources :comments
    resources :fans
  end
  # resources :songs

  resources :bands do
    resources :comments
    resources :members
    resources :albums do
      resources :songs
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'bands#index'
end

app/models/band.rb
class Band < ApplicationRecord
  default_scope { order(name: :asc) }

  has_many :members, dependent: :destroy
  has_many :albums, dependent: :destroy

  has_many :comments, as: :commentable

  validates :name, presence: true, uniqueness: true
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_band
    @band = Band.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def band_params
    params.require(:band).permit(:name, :photo, :description)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(band) do |f| %>
  <% if band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Band\'s name' %>
  </div>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.text_field :photo, class: 'form-control', placeholder: 'Band\'s photo URL', value: 'https://image.freepik.com/free-icon/multiple-users-silhouette_318-49546.jpg' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Short band description' %>
  </div>

  <div class="actions" align="right">
    <%= f.submit 'Save', class: 'btn btn-primary btn-save' %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<div class="container">

  <%= link_to 'Back', band_path(@band), class: 'btn btn-outline-info btn-sm btn-back' %>

  <h1 class="form-header">Editing Band</h1>

  <%= render 'form', band: @band %>

</div>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-name" href="/bands">Fakezone</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active nav-active" href="/bands">Bands <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link nav-normal" href="/events">Events</a>
        <a class="nav-item nav-link nav-normal" href="/fanclubs">Fanclubs</a>
      </div>
    </div>
  </nav>
</div>

<div class="container index">
  <%= link_to "Add Band", new_band_path, class: 'btn btn-outline-info' %>
  <br>
  <br>
  <div class="container">
    <div class="row">
      <div class="card-columns">
      <% @bands.each do |band| %>

        <div class="card">
          <img class="card-img-top card-style" src=<%= band.photo %>>
          <div class="card-block card-div card-name">
            <h4 class="card-title" ><%= link_to band.name, band %></h4>
            <p class="card-delete"><%= link_to 'Delete', band, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %></p>
            <div class="clear: both;"></div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bands/new.html.erb
<div class="container" >

  <%= link_to 'Back', bands_path, class: 'btn btn-outline-info btn-sm btn-back' %>

  <h1 class="form-header">Add Band</h1>

  <%= render 'form', band: @band %>

</div>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-name" href="/bands">Fakezone</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active nav-active" href="/bands">Bands <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link nav-normal" href="/events">Events</a>
        <a class="nav-item nav-link nav-normal" href="/fanclubs">Fanclubs</a>
      </div>
    </div>
  </nav>
</div>

<div class="container detail">
  <%= link_to 'Back', bands_path, class: 'btn btn-outline-info btn-sm btn-back' %>

  <h2 class="detail-header"><%= @band.name %></h2>
  <img class="detail-picture" src=<%= @band.photo %>>
  <p><%= @band.description %></p>

  <%= link_to 'Edit Band', edit_band_path(@band), class: 'btn btn-primary' %>
  <%= link_to "Add Member", new_band_member_path(@band), class: 'btn btn-primary' %>
  <%= link_to "Add Album", new_band_album_path(@band), class: 'btn btn-primary' %>
  <h3>Members:</h3>

  <% if @band.members.size > 0 %>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Instrument</th>
        <th colspan="2"></th>
      </tr>
      <% @band.members.each do |member| %>
      <tr>
        <td><%= link_to member.name, band_member_path(@band, member) %></td>
        <td><%= Time.now.year-member.age %></td>
        <td><%= member.instrument %></td>
        <td><%= link_to "Edit Member", edit_band_member_path(@band, member), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Remove Member', band_member_path(@band, member), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %></td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>There are no members yet.</p>
  <% end %>

  <h3>Albums:</h3>
  <% if @band.albums.size > 0 %>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Year</th>
        <th colspan="2"></th>
      </tr>
      <% @band.albums.each do |album| %>
      <tr>
        <td><%= link_to album.name, band_album_path(@band, album) %></td>
        <td><%= album.year %></td>
        <td><%= link_to "Edit Album", edit_band_album_path(@band, album), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Remove Album', band_album_path(@band, album), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %></td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>There are no albums yet.</p>
  <% end %>
</div>

<div class="container comment">
  <h3>Comments</h3>

  <%= form_for [@band, Comment.new] do |f| %>
  <%= f.text_area :body, class: 'form-control', placeholder: "Add a comment" %><br/>
  <%= f.submit "Add Comment", class: 'btn btn-primary btn-save' %>
  <% end %>

  <ul>
    <%= render(partial: 'comments/comment', collection: @band.comments) %>
  </ul>
</div>