config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :fanclubs do
    resources :comments
    resources :fans
  end
  # resources :songs

  resources :bands do
    resources :comments
    resources :members
    resources :albums do
      resources :songs
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'bands#index'
end

app/models/fanclub.rb
class Fanclub < ApplicationRecord
  default_scope { order(name: :asc) }

  has_many :fans, dependent: :destroy

  has_many :comments, as: :commentable

  validates :name, presence: true, uniqueness: true
end

app/controllers/fanclubs_controller.rb
class FanclubsController < ApplicationController
  before_action :set_fanclub, only: [:show, :edit, :update, :destroy]

  # GET /fanclubs
  # GET /fanclubs.json
  def index
    @fanclubs = Fanclub.all
  end

  # GET /fanclubs/1
  # GET /fanclubs/1.json
  def show
  end

  # GET /fanclubs/new
  def new
    @fanclub = Fanclub.new
  end

  # GET /fanclubs/1/edit
  def edit
  end

  # POST /fanclubs
  # POST /fanclubs.json
  def create
    @fanclub = Fanclub.new(fanclub_params)

    respond_to do |format|
      if @fanclub.save
        format.html { redirect_to @fanclub, notice: 'Fanclub was successfully created.' }
        format.json { render :show, status: :created, location: @fanclub }
      else
        format.html { render :new }
        format.json { render json: @fanclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fanclubs/1
  # PATCH/PUT /fanclubs/1.json
  def update
    respond_to do |format|
      if @fanclub.update(fanclub_params)
        format.html { redirect_to @fanclub, notice: 'Fanclub was successfully updated.' }
        format.json { render :show, status: :ok, location: @fanclub }
      else
        format.html { render :edit }
        format.json { render json: @fanclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fanclubs/1
  # DELETE /fanclubs/1.json
  def destroy
    @fanclub.destroy
    respond_to do |format|
      format.html { redirect_to fanclubs_url, notice: 'Fanclub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fanclub
    @fanclub = Fanclub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def fanclub_params
    params.require(:fanclub).permit(:name, :location, :photo, :description)
  end
end

app/helpers/fanclubs_helper.rb
module FanclubsHelper
end

app/views/fanclubs/_form.html.erb
<%= form_for(fanclub) do |f| %>
  <% if fanclub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fanclub.errors.count, "error") %> prohibited this fanclub from being saved:</h2>

      <ul>
      <% fanclub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Fanclub name' %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control', placeholder: 'Fanclub location' %>
  </div>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.text_field :photo, class: 'form-control', placeholder: 'Fanclub photo URL', value: 'https://image.freepik.com/free-icon/multiple-users-silhouette_318-49546.jpg' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Short fanclub description' %>
  </div>

  <div class="actions" align="right">
    <%= f.submit 'Save', class: 'btn btn-primary btn-save' %>
  </div>
<% end %>

app/views/fanclubs/edit.html.erb
<div class="container">

  <%= link_to 'Back', fanclub_path(@fanclub), class: 'btn btn-outline-info btn-sm btn-back' %>

  <h1 class="form-header">Editing Fanclub</h1>

  <%= render 'form', fanclub: @fanclub %>

</div>

app/views/fanclubs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-name" href="/bands">Fakezone</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link nav-normal" href="/bands">Bands <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link nav-normal" href="/events">Events</a>
        <a class="nav-item nav-link active nav-active" href="/fanclubs">Fanclubs</a>
      </div>
    </div>
  </nav>
</div>

<div class="container index">
  <%= link_to "Add Fanclub", new_fanclub_path, class: 'btn btn-outline-info' %>
  <br>
  <br>

  <div class="container">
    <div class="row">
      <div class="card-columns">
        <% @fanclubs.each do |fanclub| %>
        <div class="card">
          <img class="card-img-top card-style" src=<%= fanclub.photo %>>
          <div class="card-block card-div card-name">
            <h4 class="card-title"><%= link_to fanclub.name, fanclub %></h4>
            <p class="card-delete"><%= link_to 'Delete', fanclub, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %></p>
            <div class="clear: both;"></div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/fanclubs/new.html.erb
<div class="container">

  <%= link_to 'Back', fanclubs_path, class: 'btn btn-outline-info btn-sm btn-back' %>

  <h1 class="form-header">Add Fanclub</h1>

  <%= render 'form', fanclub: @fanclub %>

</div>

app/views/fanclubs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-name" href="/bands">Fakezone</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link nav-normal" href="/bands">Bands <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link nav-normal" href="/events">Events</a>
        <a class="nav-item nav-link active nav-active" href="/fanclubs">Fanclubs</a>
      </div>
    </div>
  </nav>
</div>

<div class="container detail">
  <%= link_to 'Back', fanclubs_path, class: 'btn btn-outline-info btn-sm btn-back' %>
  <h2 class="detail-header"><%= @fanclub.name %></h2>
  <img class="detail-picture" src=<%= @fanclub.photo %>>
  <p><strong>Location: </strong><%= @fanclub.location %></p>
  <p><strong>Description: </strong><%= @fanclub.description %></p>

  <%= link_to 'Edit Fanclub', edit_fanclub_path(@fanclub), class: 'btn btn-primary' %>
  <%= link_to "Add Fan", new_fanclub_fan_path(@fanclub), class: 'btn btn-primary' %>

  <h3>Members:</h3>
  <% if @fanclub.fans.size > 0 %>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th colspan="2"></th>
      </tr>
      <% @fanclub.fans.each do |fan| %>
      <tr>
        <td><%= link_to fan.name, fanclub_fan_path(@fanclub, fan) %></td>
        <td><%= Time.now.year-fan.age %></td>
        <td><%= link_to "Edit Fan", edit_fanclub_fan_path(@fanclub, fan), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Remove Fan', fanclub_fan_path(@fanclub, fan), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %></td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>There are no members yet.</p>
  <% end %>
</div>

<div class="container comment">
  <h3>Comments</h3>

  <%= form_for [@fanclub, Comment.new] do |f| %>
  <%= f.text_area :body, class: 'form-control', placeholder: "Add a comment" %><br/>
  <%= f.submit "Add Comment", class: 'btn btn-primary btn-save' %>
  <% end %>

  <ul>
    <%= render(partial: 'comments/comment', collection: @fanclub.comments) %>
  </ul>
</div>